from .facility_location_problem import FacilityLocationProblem
from .graph_coloring_problem import GraphColoringProblem
from .k_partition_problem import KPartitionProblem
from .maximum_clique_problem import MaximumCliqueProblem
from .set_cover_problem import SetCoverProblem
from .max_cut_problem import MaxCutProblem
# from .TSP import TravelingSalesmanProblem